notifications:
  email: false
sudo: enabled
os: linux
language: python
python: 3.7-dev
cache: pip
env:
  global:
    - GH_REPO=Drakkar-Software/OctoBot-Notifications
    - DEPLOY_BRANCH=master
    - PACKAGE_FOLDER=octobot_notifications
    - secure: BtZrj9zXZh3Zgt1S9T/6C2kLEYfNaymGGe4KbwKKQeTTR8Rk634w79V3mdqSfM8Oi4zgod/Umk1W+VqZOYHU70yQTt7H1e5pHxOLLLdgP7hesrA5IY45FiBB/WI1MIzENa7GInbduJb9nUD7DC7dZv1k8maBPWicm40c/WF4opHagiboYQZP29ZZzCdYGhlWbYwfL0yfKKgnQW39HZbElGuxz8cXINIyDZKOljynUJh5suAypVs9WZVMnEa4GUQ7WGDvy54I2/cCfzyce0fhk2mUvrxOWYaT9Mij4JkehhU4szKEHg7qRjxUc40ozKhav5MmBGoZ6NyWH4rVkTCBywobG85JWH789tsTOyGmFcYqqK1YmU4P1xoVIlF4qtByzX5HIdqDSXSgcrb+I5Qe+dGeFuJMR+URS8Iw+ouHSZP+s4+aHGOP/7DaET5cDsuzFuD2bEFC6Beuk3U8Eh4RStFYPdBzPFw2iT4VYG+upvU3LthLftvEg131TC/d4F0jEDuSGHqZksMrAdFGxQwPVUAjEB3MepGuf0AZK0Td1Fw27nnZwsj/nyvPi/fGTWUcWHni32ocYNF27DmVX2b0HAIzYOWWej1LarAwX8Sci3k7tFfo3ObKhyziLzMdkfCLLPN3C2APaQUbrZHhcUAat3YSlwqGnoh9O8Zy4C/cg6s=
    - secure: bRNGtJAVCYje6x7iY6ypwIEGDTUobY4pXu0w0esy8msjW5W4Z2/ZojH61kFsoBsmDVp2EsVh5Pat3YA52Qb6L7k5kl9gM+EcIQvN9gqOEkQMWshgIk8sE4qLKwSHYK7OeXGrYHcdGD2+6nvzJDzE1clKabPwC5K5t73Kh63V76pQ+Ki2h5mazVQT7vuvV47kCZO9ufWjY030XfSNxARdriIwPI7LkKktxjtlunKjNNe8mWSvPIyzLFOuqeKZ2ad/LFkk35jFUFJFWYJG2w8ScQJvBvkuC1j0Zk8JhLONdlxZGiAhHD5GIOfFEvjS+L1KkcWVHaGL8g7Bf5QBEXikL+8XKxv/+YxYQV+TvgD5p/Zx1WqdEsAxkfxO6iNav03chh3GBDnzFkhVeInU3QLRwBsmxYPOvmk3wAeuVvMCnrY8Xf3tiQe3xxTx881Fgyw1hRH5hMYZe1r5zDK0k2gZAYXRcT8zBPVN3Jf643KQWvAeW5e/xjykfDc8at3LC3R8HuwBUoMpmjUYsk7GTs1yVfzk+winNd4XAhiHvNxdP48fLhEDczYq14WPtVoecZAiUupbe34A30pGWO9LKvDwBCcIrckHseWUl7PbBSaj5/tA4BXmQVW7Fol4GzKmnBVWAq8XmbPXpezRvrUYHbSXRu2F+C5ku+KVi4ZK7A64JC4=

install:
  - python3 -m pip install --prefer-binary -r dev_requirements.txt -r requirements.txt

matrix:
  include:
    - name: "Linux - Python 3.7-dev - Python sources"
      stage: test
      os: linux
      python: 3.7-dev
      language: python
      script:
        - pytest --cov=. --cov-config=.coveragerc --durations=0 -rw tests
      after_success:
        - if [ $TRAVIS_PULL_REQUEST == "false" ]; then coveralls; fi

    - name: "Linux - Python 3.7-dev - Installed"
      stage: test
      os: linux
      python: 3.7-dev
      language: python
      script:
        - python3 setup.py install
        - rm -rf $PACKAGE_FOLDER
        - pytest tests

    - name: "Linux - Python 3.7-dev - Deploy"
      stage: deploy
      script:
        - ls
      deploy:
        - provider: pypi
          user: "__token__"
          password:
            secure: HHlsEgI/sKI1iG5y571xXlokPZN6nwT4wCeG1oLFX6gEJTMnyWDq8wSiqaaIiOMcs6MWA/pQI6wf4yL0a2lXZMiNQIEC+Q64Iln1leNBXbDDsNYXPHPhsb2ZIPkVf2PFFIUCp+7kNQk7+h/5Px3wmoLs2WZbqy2vMHA4fGKwA3/xrwbjovQTJbDkonyZPzPCo30jsbl5jH/IzH1Lv2hn1xK7yS2w3y+iSV9tj2Wchcfz18OAVrb59PgaQptEzlKqujP6Khj6qV+04cTldzYh2Vd0kyYlSxmSN57EKYVyZfUkXCLm/AcJ55YfNwbrGslmPC/0g8rbmlMVGwB9cHQwBLARu3QwJZ7wW1PDiCXvJ2BTbeihh8dzOneGkgwfOe3HXD1F/7zA0I4NOuucPhcyD+EA3XVzFhNSqCOrK1E9D8pMqxn3c08+ORazdcebVojF7OAODxDOt1cldPwRjjflZ2AV6vOpZZvSKq43A9n3aXDnyTmzJF5y/Q1RjdmAgqb/bCchtUQ3COq5RA7BWtYCWnZURWy3lnjBB99G24v3dR2d1L730mjN72AIqx86bvKYU7YEiwz0ZTzlWaSXUjz78I7oDkYHuQwEnEeQ8AdA78+IJU3/lgac2XuRjkVr4MDwfJm52Y1GrayOC+JvFj9axVA6jgKOfk0WSN0qZwsTim8=
          skip_cleanup: true
          skip_existing: true
          distributions: "sdist"
          on:
            repo: $GH_REPO
            branch: $DEPLOY_BRANCH
            tags: true
            condition: $TRAVIS_OS_NAME = 'linux'
        - provider: script
          script: docker run -it -e PYPI_USERNAME=$PYPI_USERNAME -e PYPI_PASSWORD=$PYPI_PASSWORD -v $(pwd):/project drakkarsoftware/octobot-pypi-deploy:i686 "i686" "cp37-cp37m" "cp37"
          skip_cleanup: true
          skip_existing: true
          on:
            repo: "$GH_REPO"
            branch: "$DEPLOY_BRANCH"
            tags: true
            condition: "$TRAVIS_OS_NAME = 'linux'"
        - provider: script
          script: docker run -it -e PYPI_USERNAME=$PYPI_USERNAME -e PYPI_PASSWORD=$PYPI_PASSWORD -v $(pwd):/project drakkarsoftware/octobot-pypi-deploy:x86_64 "x86_64" "cp37-cp37m" "cp37"
          skip_cleanup: true
          on:
            repo: "$GH_REPO"
            branch: "$DEPLOY_BRANCH"
            tags: true
            condition: "$TRAVIS_OS_NAME = 'linux'"

    - name: "OSX - Python 3.7 - Deploy"
      stage: deploy
      os: osx
      osx_image: xcode11    # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      # python: 3.7         # 'python:' is ignored on Travis CI macOS
      before_install: python3 --version ; pip3 --version ; sw_vers
      install:
        - python3 -m pip install --prefer-binary --user -r requirements.txt
        - python3 -m pip install --prefer-binary -r dev_requirements.txt
      before_cache:
        - rm -f "$HOME/Library/Caches/pip/log/debug.log"
      cache:
        directories:
          - "$HOME/Library/Caches/pip"
      script:
        - python3 setup.py build_ext --inplace
        - pytest tests
      deploy:
        - provider: script
          script: python3 setup.py bdist_wheel && python3 -m twine upload dist/* -u $PYPI_USERNAME -p $PYPI_PASSWORD --skip-existing
          skip_cleanup: true
          on:
            repo: "$GH_REPO"
            branch: "$DEPLOY_BRANCH"
            tags: true
            condition: "$TRAVIS_OS_NAME = 'osx'"
