notifications:
  email: false
sudo: enabled
os: linux
language: python
python: 3.7-dev
install:
  - python3 -m pip install --upgrade -r requirements.txt -r dev_requirements.txt

matrix:
  include:
    - name: "Linux - Python 3 nightly"
      os: linux
      python: nightly
      language: python
      script:
        - python3 setup.py install

deploy:
  - provider: pypi
    username:
      secure: BtZrj9zXZh3Zgt1S9T/6C2kLEYfNaymGGe4KbwKKQeTTR8Rk634w79V3mdqSfM8Oi4zgod/Umk1W+VqZOYHU70yQTt7H1e5pHxOLLLdgP7hesrA5IY45FiBB/WI1MIzENa7GInbduJb9nUD7DC7dZv1k8maBPWicm40c/WF4opHagiboYQZP29ZZzCdYGhlWbYwfL0yfKKgnQW39HZbElGuxz8cXINIyDZKOljynUJh5suAypVs9WZVMnEa4GUQ7WGDvy54I2/cCfzyce0fhk2mUvrxOWYaT9Mij4JkehhU4szKEHg7qRjxUc40ozKhav5MmBGoZ6NyWH4rVkTCBywobG85JWH789tsTOyGmFcYqqK1YmU4P1xoVIlF4qtByzX5HIdqDSXSgcrb+I5Qe+dGeFuJMR+URS8Iw+ouHSZP+s4+aHGOP/7DaET5cDsuzFuD2bEFC6Beuk3U8Eh4RStFYPdBzPFw2iT4VYG+upvU3LthLftvEg131TC/d4F0jEDuSGHqZksMrAdFGxQwPVUAjEB3MepGuf0AZK0Td1Fw27nnZwsj/nyvPi/fGTWUcWHni32ocYNF27DmVX2b0HAIzYOWWej1LarAwX8Sci3k7tFfo3ObKhyziLzMdkfCLLPN3C2APaQUbrZHhcUAat3YSlwqGnoh9O8Zy4C/cg6s=
    password:
        secure: bRNGtJAVCYje6x7iY6ypwIEGDTUobY4pXu0w0esy8msjW5W4Z2/ZojH61kFsoBsmDVp2EsVh5Pat3YA52Qb6L7k5kl9gM+EcIQvN9gqOEkQMWshgIk8sE4qLKwSHYK7OeXGrYHcdGD2+6nvzJDzE1clKabPwC5K5t73Kh63V76pQ+Ki2h5mazVQT7vuvV47kCZO9ufWjY030XfSNxARdriIwPI7LkKktxjtlunKjNNe8mWSvPIyzLFOuqeKZ2ad/LFkk35jFUFJFWYJG2w8ScQJvBvkuC1j0Zk8JhLONdlxZGiAhHD5GIOfFEvjS+L1KkcWVHaGL8g7Bf5QBEXikL+8XKxv/+YxYQV+TvgD5p/Zx1WqdEsAxkfxO6iNav03chh3GBDnzFkhVeInU3QLRwBsmxYPOvmk3wAeuVvMCnrY8Xf3tiQe3xxTx881Fgyw1hRH5hMYZe1r5zDK0k2gZAYXRcT8zBPVN3Jf643KQWvAeW5e/xjykfDc8at3LC3R8HuwBUoMpmjUYsk7GTs1yVfzk+winNd4XAhiHvNxdP48fLhEDczYq14WPtVoecZAiUupbe34A30pGWO9LKvDwBCcIrckHseWUl7PbBSaj5/tA4BXmQVW7Fol4GzKmnBVWAq8XmbPXpezRvrUYHbSXRu2F+C5ku+KVi4ZK7A64JC4=
    skip_existing: true
    skip_cleanup: true
    distributions: "sdist"
    on:
      repo: Drakkar-Software/OctoBot-Notifications
      branch: master
      tags: true
      condition: $TRAVIS_OS_NAME = 'linux'
